name: Deploy Next.js App to VPS

on:
  push:
    branches: [ "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy and restart app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Переходим в папку проекта
            cd /var/www/fastuser/data/www/wstudio.tech

            # Устанавливаем зависимости
            echo "📦 Устанавливаем production-зависимости..."
            npm ci --omit=dev

            # Останавливаем старое приложение
            echo "🔄 Останавливаем wstudio в PM2..."
            pm2 delete wstudio || true

            # Даём время на освобождение порта
            echo "⏳ Ждём 5 секунд..."
            sleep 5

            # Убиваем остатки
            echo "🔄 Убиваем процессы на порту 3000..."
            fuser -k 3000/tcp || true
            sleep 2

            pkill -f "next start" || true
            pkill -f "next-server" || true

            # Запускаем новое приложение
            echo "🚀 Запускаем новое приложение через PM2..."
            pm2 start "npm run start" --name "wstudio"

            # Финал
            echo "✅ Деплой завершён."